"""add related_fixed_bill_id to expenses

Revision ID: 7cda8ecf4da3
Revises: 3a9ab26a19ac
Create Date: 2026-08-15 02:49:00.544106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cda8ecf4da3'
down_revision: Union[str, None] = '3a9ab26a19ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('related_fixed_bill_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'expenses', 'fixed_bills', ['related_fixed_bill_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.drop_column('expenses', 'related_fixed_bill_id')
    # ### end Alembic commands ###
